name: ridesure_rider
description: RideSure Rider - Motorcycle ride-hailing for Zambia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  socket_io_client: ^2.0.3+1
  geolocator: ^11.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.3
  google_maps_flutter: ^2.5.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
